name: Build Notifications Docker Image

env:
  IMAGE_NAME: notifications
  AWS_REGION: eu-west-1

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Test Notifications
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          fetch-depth: '0'

      - name: Build Docker Compose Stack...
        run: |
          cd ${GITHUB_WORKSPACE}/tests
          docker-compose build

      - name: Run Notifications Image Test
        run: |
          cd ${GITHUB_WORKSPACE}/tests
          docker-compose up --abort-on-container-exit --exit-code-from tester tester