name: Test Notifications Docker Image

on:
  pull_request:
  workflow_call:

jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
      - name: Detect secrets
        uses: alphagov/pay-ci/actions/detect-secrets@master
  test:
    name: Test Notifications
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
        with:
          fetch-depth: '0'

      - name: Build Docker Compose Stack...
        run: |
          cd ${GITHUB_WORKSPACE}/tests
          docker-compose build

      - name: Run Notifications Image Test
        run: |
          cd ${GITHUB_WORKSPACE}/tests
          docker-compose up --abort-on-container-exit --exit-code-from tester tester
